### ISSUE TITLE
Add a small colored elephpant to the "newest herd" list

### ISSUE THREAD

**Issue by ramondelafuente** [f500/elewant#100]
In the "newest herd" list there are breed names, but it would be nicer to see an actual colored elephpant. All ElePHPants in the herd could be shown in a grid instead of the name in text.

**Comment by Gwendolyn68** [comment]
I will try and pick up on this issue. Not sure I will succeed tho ;-)

**Comment by Gwendolyn68** [comment]
I made a pull request for this issue.
See: https://github.com/f500/elewant/pull/149

I hope this is what you had in mind :)

**Comment by ramondelafuente** [comment]
The current text-based list does a pretty decent job; it was my _bad idea_ to suggest anything different.

Closing this one.
