### ISSUE TITLE
Add some statistics!

### ISSUE THREAD

**Issue by ramondelafuente** [f500/elewant#103]
Some statistics we can show right away would be:

- [ ] Top 5 most diverse herds (largest number of distinct breeds)
- [ ] Top 5 largest herds (largest number of elephpants in total)
- [x] Total number of herds
- [ ] Total number of ElePHPants known
- [ ] Total number of ElePHPants of a certain type wanted
- [x] Total number of new Herds formed since

And some fun stuff like Total number of herds and total number of elephpants known.

**Comment by ramondelafuente** [comment]
Number of ElePHPants of a certain type wanted.

**Comment by ramondelafuente** [comment]
If #137 is merged, there will be a HerdingStatisticsCalculator service that can be used to generate statistics. It could be expanded to calculate more statistics, to be used on a statistics page...

**Comment by edwinkortman** [comment]
On it!
