### ISSUE TITLE
UX: Post-authorize dead end

### ISSUE THREAD

**Issue by dennisdegreef** [f500/elewant#110]
The main page shows the user an impression and feel for the project, with a centralized 'click me!'-like button.

This button follows through to inform you that you need to authorize your twitter account. 

After authorizing the twitter oauth, the following message shows:
`SUCCESSFULLY REGISTERED AND CONNECTED THE ACCOUNT "$accountName"!`

After looking around a big white page, I notice that I am logged in, and can press a menu option to continue.

I would suggest the following:
- Continue the story and the the user on a journey through your application (maybe Wizard-style to get them familiar with your domain language).
- Add some buttons to start adding to the herd (or the goal of your application).
- Something else that prevents the user from thinking "What now?"

EDIT: Maybe just redirect to the main page directly, since this seems to be exactly that, after login.

**Comment by ramondelafuente** [comment]
@jaspernbrouwer The feature you are working on is being requested :)
