### ISSUE TITLE
Add "rename herd" command

### ISSUE THREAD

**Issue by ramondelafuente** [f500/elewant#121]
A herd is created with the "display name" of a user on registration. But Shepherds should be able to change the names of their Herds!

A "rename herd" changes the "name" property of the Herd aggregate. It should be possible on the "herd management" page `/herd/tending`.

**Comment by Gwendolyn68** [comment]
I'll take a look at this one. Don't promise anything tho ;-)

**Comment by ramondelafuente** [comment]
Oh I'm actually almost done with this (working on it right now as a matter of fact). Sorry that I didn't put it in progress before :(

**Comment by ramondelafuente** [comment]
I would like a PR review for it when I'm done, if you want to? I'm using it as an example for how to add commands...

**Comment by Gwendolyn68** [comment]
I can try. Any suggestions on something I could work on? Would have been nice if you would have been in Manchester ;-)

**Comment by ramondelafuente** [comment]
@Gwendolyn68  You could take a look at #126, add the Roave ElePHPant. It was _just_ released on the [Field Guide](http://afieldguidetoelephpants.net/). Exciting times!

When adding a ElePHPant, there are three aspects to add:
- Inside the Herding domain model, the concept of a Breed is captured in a class called Breed. The Roave elePHPant will be GRAY_ROAVE_REGULAR  (there is no LARGE variant for this one).
- The translation. Each ElePHPant breed is translated to a more user-friendly name. This one is just 'Roave'.
- The style. Each ElePHPant breed has a defined color. Since there is already a "grey", the color will be gray by default, but if you find this ElePHPant needs a specific gray color, you could add a style for .elephpant.gray.roave...

You can look at the previously added ElePHPant as an example: #130 
Good luck!

**Comment by ramondelafuente** [comment]
@Gwendolyn68 I forgot to tag you in the comment above, so to  make sure I'm tagging you again ;)

**Comment by Gwendolyn68** [comment]
Sorry Ramon, I could have mentioned earlier, but after phpnw I went to visit my friend who lives in North Wales and this is the first time I open my laptop again. 
Upcoming wednesday I will see Marieke for a day of pairprogramming, we might pick up on one of the still open items.
