### ISSUE TITLE
Please add the Roave elephpant

### ISSUE THREAD

**Issue by asgrim** [f500/elewant#126]
As per title! Should start existing next month or so :)

**Comment by ramondelafuente** [comment]
Hey! Sure thing :)

We're using <http://afieldguidetoelephpants.net/> as the single source of truth, I see there's already an issue in the repo there :) 👍

**Comment by asgrim** [comment]
Note: there is only the regular variety of the Roave elePHPant, no large ones :)

**Comment by asgrim** [comment]
Fwiw, the Roave elephpant is live on afieldguidetoelephpants :)

**Comment by ramondelafuente** [comment]
Cool stuff! We should have Roave on board very soon. 👍

**Comment by Gwendolyn68** [comment]
I have created a pull request for this issue.
See: https://github.com/f500/elewant/pull/148

**Comment by asgrim** [comment]
Hmm; I noticed @Gwendolyn68 made a PR to add this, but it's not appearing on the site yet; is there something missing here? Or maybe just awaiting deployment or something?

**Comment by ramondelafuente** [comment]
Yeah, it was that... so busy building features that nobody deployed the stuff that was finished!
Done now.

**Comment by asgrim** [comment]
Awesome, thank you @Gwendolyn68 and @ramondelafuente! :heart:
