### ISSUE TITLE
Scrutinizer

### ISSUE THREAD

**Issue by edwinkortman** [f500/elewant#172]
I came across this tool in different open source project and it appears to be quite interesting: 
https://scrutinizer-ci.com/g/hautelook/AliceBundle/issues/master

It does a lot of things and it is free for open source projects! Could it be useful for Elewant to maintain security, a coding standard etc.? 
https://scrutinizer-ci.com/continuous-analysis

**Comment by ramondelafuente** [comment]
I'm getting email from Scrutinizer, so I assume we're all up and running :D
