### ISSUE TITLE
RebuildHerdProjectionCommand no longer works

### ISSUE THREAD

**Issue by edwinkortman** [f500/elewant#194]
`src/Elewant/AppBundle/Command/RebuildHerdProjectionCommand.php`
This file contains a call to a `replay` function on the EventStore that no longer exists.

**Comment by ramondelafuente** [comment]
This one is solved because we're now using a Prooph projection.
These can be run through a console commands:
```
bin/console event-store:projections:run herd_projection
bin/console event-store:projections:reset herd_projection
```
