### ISSUE TITLE
Keep the location information from Twitter

### ISSUE THREAD

**Issue by ramondelafuente** [f500/elewant#51]
Twitter gives location information that we can use as a basic value for a Herd location. It probably For Herds, we will use Lat/Long later.

**Comment by jaspernbrouwer** [comment]
We already store the location in the user, but the user isn't used in the Herding domain. So we still need to add it to the herd.

Maybe add location to the `UserHasRegistered` event?

**Comment by jaspernbrouwer** [comment]
I've added this one the the "first release", because we can't reply `UserHasRegistered` events like we can with the Prooph events.

**Comment by ramondelafuente** [comment]
I'm closing this one, as discussed we will try to put this in the model as "RelocateHerd" command
